# Generated by Django 4.2.2 on 2023-06-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_tag_project_vote_ratio_project_vote_total_review_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="vote",
        ),
        migrations.AlterField(
            model_name="review",
            name="value",
            field=models.CharField(
                choices=[("up", "Up Vote"), ("down", "Down Vote")], max_length=200
            ),
        ),
    ]
